### PR TITLE
Copy/Maggie & James' bio pages

### PR DESCRIPTION
**Pull request by avinashi10**
## Description
This PR adds copy to Maggie & James' bios, completing their bio pages. 

## Related Tickets & Documents
This was done in support of our design team, as they needed help with the copy.

## What type of PR is this? (check all applicable)

|     | Type                       |
| --- | -------------------------- |
|     | :sparkles: New feature     |
|  ✓  | ✏️  Copy     |
|     | 🎨 Style                   |
|     | :hammer: Refactoring       |
|     | 🔥 Performance Improvements|
|     | :bug: Bug fix              |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Mobile & Desktop Screenshots/Recordings
Screenshot 2023-11-14 at 11 34 07 AM

## What I learned
Since `fullDataSet` is stored once as a `useRef` when Vite is initially run, you need to re-run Vite to see changes made to `bioData.js`

## Testing steps

1. Switch to this branch with the following command: `git switch feature/maggie-bio-page`
2. Run the following scripts: `npm run dev` to start Vite's dev build & `npm run tailwind` to start the Tailwind CSS build
3. View the app in browser (the `npm run dev` script will return the url you can see the app at)
4. Navigate to the the Resources page and then to Maggie's bio page and James' bio page. 
5. On each bio page, read through the copy, check for typos, makes suggestions, and check the links to make sure they work.

## Added to documentation?

|     | Type                       |
| --- | -------------------------- |
|     | 📜 README.md    |
|  ✓ | 🙅 no documentation needed    |

## What gif best describes this PR or how it makes you feel?
yay

### CODE REVIEW

**Comment by Havana82** [comment]
Looks awesome ! The only thing is the question of how did the professional overcome imposter syndrome. I think that was supposed to include personal strategies or mind sets they used to overcome imposter syndrome. Like Maggie seeing her dyslexia as a blessing rather than a curse.

**Review by shyusu4 — APPROVED** [review]

**Review by bluegreen16 — CHANGES_REQUESTED** [review]
Ok, I think these are looking good! For consistency, can we please:

1. remove all honorifics (Dr.) 
2. use first and last names only for the header below their picture
3. use first names only in the body copy

Thank you.

**Comment by avinashi10** [comment]
@Havana82 Good call on that, I was only looking at the data set, and that key name is `career`, I didn't realize that career correlates with the "How did they overcome imposter syndrome?" question so I focused it on their career. I will edit it.

**Comment by avinashi10** [comment]
@bluegreen16 a case for keeping in honorifics (which we can update to do consistently across all bios) - women and other marginalized genders face a lot of discrimination in their professional fields, especially when they're minorities. They are proven to be referred to as 'dr' less often than male counterparts and it often diminishes their contributions and achievements to their field (here's an article for context: https://www.theswaddle.com/why-women-academics-with-ph-d-s-are-often-not-called-dr)

**Comment by bluegreen16** [comment]
@avinashi10 Let's keep the honorifics for sure. That means we need it to read "Dr. James Makokis", "Dr. Maggie Aderin-Pocock", and "Dr. Jedidah Isler" for their cards and for the headers below their bio page images. Everywhere else in the copy, we can refer to them as "Dr. James", "Dr. Maggie", and "Dr. Jedidah". Please let me know your thoughts.

**Comment by bluegreen16** [comment]
@avinashi10 @shyusu4 @Havana82 Kayla and I are finalizing the copy to reflect the use of honorifics and last names. We'll get it to you ASAP. And if a rewrite for James isn't feasible, no worries; just let us know.

**Comment by Havana82** [comment]
Closing this because its merged to bio updates

**Pull request closed without merging**
